package com.leon.carfixfactory.beanDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leon.carfixfactory.bean.WorkerInfo;

import com.leon.carfixfactory.beanDao.WorkerInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workerInfoDaoConfig;

    private final WorkerInfoDao workerInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workerInfoDaoConfig = daoConfigMap.get(WorkerInfoDao.class).clone();
        workerInfoDaoConfig.initIdentityScope(type);

        workerInfoDao = new WorkerInfoDao(workerInfoDaoConfig, this);

        registerDao(WorkerInfo.class, workerInfoDao);
    }
    
    public void clear() {
        workerInfoDaoConfig.clearIdentityScope();
    }

    public WorkerInfoDao getWorkerInfoDao() {
        return workerInfoDao;
    }

}
